remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Predicting Game Result at 15 Minutes]
description:
  [
    With an accuracy of 75%, my model determines the winner of a League of Legends game 15-minutes into the match.,
  ]
