remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Predicting Game Result at 15 Minutes]
description:
  [
    We are able to predict with 75% accuracy the victor of a game simply by looking at the data 15 minutes into the game.,
  ]
